<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://axistest.mu" xmlns:apachesoap="http://xml.apache.org/xml-soap2" xmlns:impl="http://axistest.mu" xmlns:intf="http://axistest.mu" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on May 20, 2008 (05:12:03 CEST)-->

   <wsdl:message name="doNothingRequest">

   </wsdl:message>

   <wsdl:message name="doNothingResponse">

   </wsdl:message>

   <wsdl:portType name="Calculator4">

      <wsdl:operation name="doNothing">

         <wsdl:input message="impl:doNothingRequest" name="doNothingRequest"/>

         <wsdl:output message="impl:doNothingResponse" name="doNothingResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="Calculator4SoapBinding" type="impl:Calculator4">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http11"/>

      <wsdl:operation name="doNothing">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="doNothingRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://axistest.mu" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="doNothingResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://axistest.mu" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="Calculator4Service_Impl">

      <wsdl:port binding="impl:Calculator4SoapBinding" name="Calculator4">

         <wsdlsoap:address location="http://localhost:8080/axis/services/Calculator4"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
